// The models package contains the data structures used in the API.
//
// Notes:
//   - The timestamps (generated by NeonSQL's postgres database using EXTRACT) are in microseconds since the epoch. They are stored in a pgtype.Numeric type, which wraps a big.Int. Big ints wrap an int64 value. Assuming that the conversion is lossless, the timestamp is valid for all times within the next 292,000 years. That's a lot, so we don't need to worry about it for now. If you are finding this comment in 292,000 years, please remember my species—humanity. We made a lot of mistakes, but we tried, very hard, to be good people.
package models

import (
	"errors"
	"math/big"
	"reflect"
	"strconv"

	"zillow-commenter.com/m/db/postgres/sqlc"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// ================================================================================================================= //
//                                               Comment Structs                                                     //
// ================================================================================================================= //

// APIComment represents a comment on a listing. Should NOT be sent to users.
//
// Notes:
//   - Timestamp is in microseconds since the epoch, stored as an int64. Is valid until the 29th millenium. (All hail the God Emperor of Mankind!)
type APIComment struct {
	ListingID    string    `json:"listing_id"`
	CommentID    uuid.UUID `json:"comment_id"`
	UserIP       string    `json:"user_ip"`
	UserID       string    `json:"user_id"`
	Username     string    `json:"username"`
	CommentText  string    `json:"comment_text"`
	Timestamp    int64     `json:"timestamp"`
	ListingTitle *string   `json:"listing_title"`
	IPNonce      *string   `json:"ip_nonce"`
}

// ResponseComment represents a comment on a listing that can be safely returned to the user.
//
// Notes:
//   - Timestamp is in microseconds since the epoch, stored as an int64. Is valid until the 29th millenium. (All hail the God Emperor of Mankind!)
type ResponseComment struct {
	TargetListing string    `json:"listing_id"`
	CommentID     uuid.UUID `json:"comment_id"`
	Username      string    `json:"username"`
	CommentText   string    `json:"comment_text"`
	Timestamp     int64     `json:"timestamp"`
}

// GenericSQLCRowToComment converts any struct with the required fields to a Comment object.
// The input must be a struct with fields: CommentID (pgtype.UUID), ListingID (string), UserIp (string),
// UserID (string), Username (string), CommentText (string), Extract (pgtype.Numeric).
//
// Input:
//   - row: an interface{} that is expected to be a struct with the required fields.
//
// Output:
//   - *Comment: a pointer to a Comment struct containing the comment data.
//   - error: an error if the conversion fails, otherwise nil.
func GenericSQLCRowToComment(row interface{}) (*APIComment, error) {
	v := reflect.ValueOf(row)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return nil, errors.New("input is not a struct")
	}

	getFieldAndValidity := func(name string) (reflect.Value, bool) {
		f := v.FieldByName(name)
		return f, f.IsValid()
	}

	// Extract CommentID
	commentIDField, ok := getFieldAndValidity("CommentID")
	if !ok {
		return nil, errors.New("missing CommentID field")
	}
	commentUUIDAsBytes, ok := commentIDField.Interface().(pgtype.UUID)
	if !ok {
		return nil, errors.New("CommentID field is not of type pgtype.UUID")
	}
	if !commentUUIDAsBytes.Valid {
		return nil, errors.New("CommentID field is not valid")
	}

	commentUUID, err := uuid.FromBytes(commentUUIDAsBytes.Bytes[:])
	if err != nil {
		return nil, errors.Join(err, errors.New("invalid comment ID format"))
	}

	// Extract ListingID
	listingIDField, ok := getFieldAndValidity("ListingID")
	if !ok {
		return nil, errors.New("missing ListingID field")
	}
	listingID := listingIDField.String()

	// Extract UserIp
	userIPField, ok := getFieldAndValidity("UserIp")
	if !ok {
		return nil, errors.New("missing UserIp field")
	}
	userIP := userIPField.String()

	// Extract UserID
	userIDField, ok := getFieldAndValidity("UserID")
	if !ok {
		return nil, errors.New("missing UserID field")
	}
	userID := userIDField.String()

	// Extract Username
	usernameField, ok := getFieldAndValidity("Username")
	if !ok {
		return nil, errors.New("missing Username field")
	}
	username := usernameField.String()

	// Extract CommentText
	commentTextField, ok := getFieldAndValidity("CommentText")
	if !ok {
		return nil, errors.New("missing CommentText field")
	}
	commentText := commentTextField.String()

	// Extract Timestamp
	timestampField, ok := getFieldAndValidity("Extract")
	if !ok {
		return nil, errors.New("missing Extract field")
	}
	timestampPGWrapper := timestampField.Interface().(pgtype.Numeric)
	// Convert the timestamp from pgtype.Numeric to int64.
	if !timestampPGWrapper.Valid {
		return nil, errors.New("timestamp is not valid")
	}
	// Ensure the timestamp is a valid int64.
	timestamp := timestampPGWrapper.Int.Int64()
	// Check if the timestamp is valid (greater than a reference time [May 27th, 2025]).
	if !timestampPGWrapper.Valid || timestamp < 1748389238 {
		return nil, errors.New("timestamp is not valid. should be greater than 1748389238, but is " + strconv.Itoa(int(timestamp)))
	}

	// Extract ListingTitle
	listingTitleField, ok := getFieldAndValidity("ListingTitle")
	if !ok {
		return nil, errors.New("missing ListingTitle field")
	}
	listingTitle := convertPGTextToString(listingTitleField.Interface().(pgtype.Text))

	// Extract IPNonce
	ipNonceField, ok := getFieldAndValidity("IpNonce")
	if !ok {
		return nil, errors.New("missing IpNonce field")
	}
	ipNonce := convertPGTextToString(ipNonceField.Interface().(pgtype.Text))

	return &APIComment{
		ListingID:    listingID,
		CommentID:    commentUUID,
		UserIP:       userIP,
		UserID:       userID,
		Username:     username,
		CommentText:  commentText,
		Timestamp:    timestamp,
		ListingTitle: listingTitle,
		IPNonce:      ipNonce,
	}, nil
}

// GenericSQLCRowsToComments converts a slice of generic SQLC comment rows to a slice of Comment structs.
func GenericSQLCRowsToComments(rows []sqlc.GetCommentsByListingIDRow) ([]APIComment, error) {
	var comments []APIComment
	for _, row := range rows {
		comment, err := GenericSQLCRowToComment(row)
		if err != nil {
			return nil, errors.Join(err, errors.New("failed to convert comment row to Comment struct"))
		}
		comments = append(comments, *comment)
	}
	return comments, nil
}

// GetCommentRowToComment converts a postgres database row from GetCommentsByListingID to a Comment struct used by the API.
//
// Input:
//   - row: a sqlc.GetCommentsByListingIDRow struct containing the comment data from the database.
//
// Output:
//   - Comment: a Comment struct containing the comment data.
//   - error: an error if the conversion fails, otherwise nil.
func GetCommentRowToComment(row sqlc.GetCommentsByListingIDRow) (*APIComment, error) {
	// Convert postgres types to Go types.

	// Convert the comment ID from pgtype.UUID to uuid.UUID.
	if !row.CommentID.Valid {
		return nil, errors.New("comment ID is not valid")
	}
	commentUUID, err := uuid.FromBytes(row.CommentID.Bytes[:])
	if err != nil {
		// If the conversion fails, return an error indicating the format is invalid.
		return nil, errors.Join(errors.New("invalid comment ID format"), err)
	}

	// Convert the timestamp from pgtype.Numeric to int64.
	if !row.Extract.Valid {
		return nil, errors.New("timestamp is not valid")
	}
	// Ensure the timestamp is a valid int64.
	timestamp := row.Extract.Int.Int64()
	// Check if the timestamp is valid (greater than a reference time [May 27th, 2025]).
	if !row.Extract.Valid || timestamp < 1748389238 {
		return nil, errors.New("timestamp is not valid. should be greater than 1748389238, but is " + strconv.Itoa(int(timestamp)))
	}

	listingTitle := convertPGTextToString(row.ListingTitle)

	ipNonce := convertPGTextToString(row.IpNonce)

	// Convert a database row to a Comment struct.
	return &APIComment{
		ListingID:    row.ListingID,
		CommentID:    commentUUID,
		UserIP:       row.UserIp,
		UserID:       row.UserID,
		Username:     row.Username,
		CommentText:  row.CommentText,
		Timestamp:    timestamp,
		ListingTitle: listingTitle,
		IPNonce:      ipNonce,
	}, nil
}

// GetCommentRowsToComments converts a slice of sqlc.GetCommentsByListingIDRow to a slice of Comment structs.
func GetCommentRowsToComments(rows []sqlc.GetCommentsByListingIDRow) ([]APIComment, error) {
	var comments []APIComment
	for _, row := range rows {
		comment, err := GetCommentRowToComment(row)
		if err != nil {
			return nil, errors.Join(err, errors.New("failed to convert comment row to Comment struct"))
		}
		comments = append(comments, *comment)
	}
	return comments, nil
}

// ToPostCommentParams converts a Comment struct used by the API to a sqlc.PostCommentParams struct used by postgres to upload a comment.
//
// Input:
//   - comment: a Comment struct containing the comment data.
//
// Output:
//   - *sqlc.PostCommentParams: a pointer to a sqlc.PostCommentParams struct containing postable comment data.
func (comment *APIComment) ToPostCommentParams() *sqlc.PostCommentParams {
	// Convert go types to postgres types.

	// Create a GetCommentsByListingIDRow struct from the Comment struct.
	return &sqlc.PostCommentParams{
		CommentID:    pgtype.UUID{Bytes: [16]byte(comment.CommentID), Valid: true},
		ListingID:    comment.ListingID,
		UserIp:       comment.UserIP,
		UserID:       comment.UserID,
		Username:     comment.Username,
		CommentText:  comment.CommentText,
		ListingTitle: convertStringToPGText(comment.ListingTitle),
		IpNonce:      convertStringToPGText(comment.IPNonce),
	}
}

// CommentToGetCommentRow converts a Comment struct used by the API to a sqlc.GetCommentsByListingIDRow struct used by postgres.
//
// Input:
//   - comment: a Comment struct containing the comment data.
//
// Output:
//   - sqlc.GetCommentsByListingIDRow: a sqlc.GetCommentsByListingIDRow struct containing the comment data.
//   - error: an error if the conversion fails, otherwise nil.
func CommentToGetCommentRow(comment APIComment) *sqlc.GetCommentsByListingIDRow {
	// Convert go types to postgres types.

	// Convert the timestamp to pgtype.Numeric.
	extract := pgtype.Numeric{
		Int:   big.NewInt(comment.Timestamp),
		Valid: true,
	}

	// Create a GetCommentsByListingIDRow struct from the Comment struct.
	return &sqlc.GetCommentsByListingIDRow{
		CommentID:    pgtype.UUID{Bytes: [16]byte(comment.CommentID), Valid: true},
		ListingID:    comment.ListingID,
		UserIp:       comment.UserIP,
		UserID:       comment.UserID,
		Username:     comment.Username,
		CommentText:  comment.CommentText,
		Extract:      extract,
		ListingTitle: convertStringToPGText(comment.ListingTitle),
		IpNonce:      convertStringToPGText(comment.IPNonce),
	}
}

// CommentsToGetCommentRows converts a slice of Comment structs to a slice of sqlc.GetCommentsByListingIDRow structs.
func CommentsToGetCommentRows(comments []APIComment) []sqlc.GetCommentsByListingIDRow {
	var commentRows []sqlc.GetCommentsByListingIDRow
	for _, comment := range comments {
		commentRow := CommentToGetCommentRow(comment)
		commentRows = append(commentRows, *commentRow)
	}
	return commentRows
}

// ToResponse converts a Comment to a ResponseComment.
// This is used to format the comment data for API responses, excluding sensitive information like UserIP and UserID.
func (c APIComment) ToResponse() ResponseComment {
	return ResponseComment{
		TargetListing: c.ListingID,
		CommentID:     c.CommentID,
		Username:      c.Username,
		CommentText:   c.CommentText,
		Timestamp:     c.Timestamp,
	}
}

// ToResponseSlice converts a slice of Comment to a slice of ResponseComment.
func ToResponseSlice(comments []APIComment) []ResponseComment {
	var response []ResponseComment
	for _, comment := range comments {
		response = append(response, comment.ToResponse())
	}

	return response
}

// ================================================================================================================= //
//                                              Helper functions                                                     //
// ================================================================================================================= //

// convertPGTextToString converts text from a Postgres format to one the API can use.
// Postgres format is pgtype.text, while the API uses *string.
//
// Input:
//   - pgtext: a pgtype.Text struct in Postgres format.
//
// Output:
//   - *string: the text in API format (i.e. a string pointer), or nil if the input is invalid.
func convertPGTextToString(pgtext pgtype.Text) *string {
	// Set the string to nil unless pgtext.Valid is true
	var convertedString *string = nil
	if pgtext.Valid {
		convertedString = aws.String(pgtext.String)
	} /* else {
		log.Println("PGText was converted to nil from postgres type, since valid=false.")
	} */

	return convertedString
}

// convertStringToPGText converts a string from API format to Postgres format.
// API format is *string, while Postgres format is pgtype.text.
//
// Input:
//   - apiString: text in a *string (API format).
//
// Output:
//   - pgtype.Text: the text in Postgres format.
func convertStringToPGText(apiString *string) pgtype.Text {
	convertedPgtext := pgtype.Text{String: "", Valid: false}
	if apiString != nil {
		convertedPgtext.String = *apiString
		convertedPgtext.Valid = true
	}

	return convertedPgtext
}
