openapi: 3.0.3
info:
  title: Zillowette Comments API
  version: 1.0.0
  description: API for managing comments on Zillow listings.

servers:
  - url: https://{restapi_id}.execute-api.{region}.amazonaws.com/{stage}
    variables:
      restapi_id:
        default: your-api-id
        description: AWS API Gateway Rest API ID
      region:
        default: us-east-1
        description: AWS region
      stage:
        default: prod
        description: Deployment stage

paths:
  /api/v1/comments/{listing_id}:
    get:
      summary: Get comments for a listing
      parameters:
        - name: listing_id
          in: path
          required: true
          schema:
            type: string
          description: The Zillow listing ID
      responses:
        '200':
          description: List of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommentResponse'
        '404':
          description: Listing not found
        '500':
          description: Internal server error

  /api/v1/comments:
    post:
      summary: Post a comment to a listing
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                listing_id:
                  type: string
                user_id:
                  type: string
                username:
                  type: string
                comment_text:
                  type: string
              required:
                - listing_id
                - user_id
                - username
                - comment_text
      responses:
        '201':
          description: Comment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommentResponse'
        '400':
          description: Invalid input data
        '500':
          description: Internal server error
  api/v1/user/user_id:
    get:
      summary: Generate a new user ID
      responses:
        '200':
          description: Generated user ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
        '500':
          description: Internal server error

components:
  schemas:
    CommentResponse:
      type: object
      properties:
        comment_id:
          type: string
          format: uuid
        listing_id:
          type: string
        user_id:
          type: string
        username:
          type: string
        comment_text:
          type: string
        user_ip:
          type: string
        timestamp:
          type: integer
          format: int64
