// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Blacklist struct {
	BlacklistID int32
	Cause       string
	UserIp      string
	UserID      pgtype.Text
	Username    pgtype.Text
	DateCreated pgtype.Timestamp
}

type Comment struct {
	CommentID   int32
	ListingID   string
	UserIp      string
	UserID      string
	Username    string
	CommentText string
	DateCreated pgtype.Timestamp
}
