package sqlc

import (
	"errors"
	"log"
	"math/big"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// ===================================================================================================================== //
//                                                   Test Helpers                                                        //
// ===================================================================================================================== //

// Stub struct to simulate a generic database row.
type FakePGRowStruct struct {
	CommentID    pgtype.UUID
	ListingID    string
	UserIp       string
	UserID       string
	Username     string
	CommentText  string
	Extract      pgtype.Numeric
	ListingTitle pgtype.Text
	IpNonce      pgtype.Text
}

// Helper to create a valid PostCommentParams
type ValidPostCommentParamsType int

const (
	ValidParamsIPv4 ValidPostCommentParamsType = iota
	ValidParamsIPv6
	ValidParamsAltIPv4
)

func GetValidPostCommentParams(paramType ValidPostCommentParamsType) PostCommentParams {
	// Create a valid CommentID
	commentID, err := GetValidPGTypeUUID()
	if err != nil {
		log.Fatal("Failed to create valid CommentID", err)
	}

	// Create a valid userID
	userID, err := uuid.NewV7()
	if err != nil {
		log.Fatal("Failed to create valid UUID for UserID", err)
	}

	switch paramType {
	case ValidParamsIPv6:
		return PostCommentParams{
			CommentID:    *commentID,
			ListingID:    "654321",
			UserIp:       "3e220f2bf981113f9b5f597168a8e13514b75a9fe9268b68e662fda5386bfb4a9490e8341315c399316cace7f41b61f7a5404fe7c04969",
			UserID:       userID.String(),
			Username:     "TestUserIPv6",
			CommentText:  "This is a valid IPv6 comment.",
			ListingTitle: pgtype.Text{String: "Regular title", Valid: true},
			IpNonce:      pgtype.Text{String: "0d00ad4b080209200aa852f2", Valid: true},
		}
	case ValidParamsAltIPv4:
		return PostCommentParams{
			CommentID:    *commentID,
			ListingID:    "789012",
			UserIp:       "9d8787f71c30a79d519688a4054b4b8a363af95e8f4b7e5b",
			UserID:       userID.String(),
			Username:     "TestUserAltIPv4",
			CommentText:  "This is another valid IPv4 comment.",
			ListingTitle: pgtype.Text{String: "Regular title", Valid: true},
			IpNonce:      pgtype.Text{String: "bdc990f0a33e852bd0e412dc", Valid: true},
		}
	default: // ValidParamsIPv4
		return PostCommentParams{
			CommentID:    *commentID,
			ListingID:    "123456",
			UserIp:       "bd98b9c5db0655b23e47a57ba65c2b7446bf1c08b39ac3173e89ab",
			UserID:       userID.String(),
			Username:     "TestUser",
			CommentText:  "This is a valid comment.",
			ListingTitle: pgtype.Text{String: "Regular title", Valid: true},
			IpNonce:      pgtype.Text{String: "1ee7385a435e4cc5e534b051", Valid: true},
		}
	}
}

// Helper to create a valid pgtype.UUID
func GetValidPGTypeUUID() (*pgtype.UUID, error) {
	newUUID, err := uuid.NewV7()
	if err != nil {
		return nil, errors.Join(errors.New("failed to generate UUID"), err)
	}

	return &pgtype.UUID{Bytes: [16]byte(newUUID), Valid: true}, nil
}

// --- For GenericRowToComment tests ---

// GetValidPGTypeNumeric creates a valid pgtype.Numeric for testing.
func GetValidPGTypeNumeric(val int64) pgtype.Numeric {
	return pgtype.Numeric{
		Int:   big.NewInt(val),
		Valid: true,
	}
}

// GetGenericPGTypeTimestamp returns a pgtype.Numeric representing a real timestamp generated by the database.
func GetGenericPGTypeTimestamp() pgtype.Numeric {
	// Based on this real time generated by the DB: {1751643582028156 -6 false finite true}}
	return pgtype.Numeric{
		Int:              big.NewInt(1751643582028156),
		Exp:              -6,
		NaN:              false,
		InfinityModifier: pgtype.Finite,
		Valid:            true,
	}
}

// Arbitrary row structure that should be convertible to a Comment.
func GetDefaultFakeRow() FakePGRowStruct {
	commentID, _ := GetValidPGTypeUUID()
	userID, _ := uuid.NewV7()
	return FakePGRowStruct{
		CommentID:    *commentID,
		ListingID:    "1234567",
		UserIp:       "9f67720a05fb8ca4781f1cb5fc60b8ab7a2b068bf2be9f0660",
		UserID:       userID.String(),
		Username:     "tester",
		CommentText:  "hello",
		Extract:      GetValidPGTypeNumeric(time.Now().UnixMicro()),
		ListingTitle: pgtype.Text{String: "test title", Valid: true},
		IpNonce:      pgtype.Text{String: "96dc49a63b34dcf9229c0ed5", Valid: true},
	}
}

// Default PostCommentRow for testing.
func GetDefaultPostCommentRow() PostCommentRow {
	commentID, _ := GetValidPGTypeUUID()
	userID, _ := uuid.NewV7()
	return PostCommentRow{
		CommentID:    *commentID,
		ListingID:    "1234567",
		UserIp:       "9f67720a05fb8ca4781f1cb5fc60b8ab7a2b068bf2be9f0660",
		UserID:       userID.String(),
		Username:     "tester",
		CommentText:  "hello",
		Extract:      GetValidPGTypeNumeric(time.Now().UnixMicro()),
		ListingTitle: pgtype.Text{String: "test title", Valid: true},
		IpNonce:      pgtype.Text{String: "96dc49a63b34dcf9229c0ed5", Valid: true},
	}
}

// Default GetCommentsByListingIDRow for testing.
func GetDefaultGetCommentRow() GetCommentsByListingIDRow {
	commentID, _ := GetValidPGTypeUUID()
	userID, _ := uuid.NewV7()
	return GetCommentsByListingIDRow{
		CommentID:    *commentID,
		ListingID:    "1234567",
		UserIp:       "9f67720a05fb8ca4781f1cb5fc60b8ab7a2b068bf2be9f0660",
		UserID:       userID.String(),
		Username:     "tester",
		CommentText:  "hello",
		Extract:      GetValidPGTypeNumeric(time.Now().UnixMicro()),
		ListingTitle: pgtype.Text{String: "test title", Valid: true},
		IpNonce:      pgtype.Text{String: "96dc49a63b34dcf9229c0ed5", Valid: true},
	}
}
