# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Backend

on:
  push:
    branches:
      ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: |
          cd backend
          go mod tidy
          echo "$(<go.mod)"

      - name: Test Input Validation
        env:
          CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING }}
          TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
        run: |
          cd backend
          go test -v ./db/postgres/sqlc

      - name: Run Blackbox API Tests
        env:
          API_IP: ${{ secrets.API_IP }}
        run : |
          cd backend
          go test -v ./api/blackbox_tests
      
      - name: Run Comment Struct Conversion Tests
        run: |
          cd backend
          go test -v ./api/models
