# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Backend

on:
  push:
    branches:
      ["master", "dev"]
  pull_request:
    branches: ["master", "dev"]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: |
          cd back_end
          go mod tidy
          echo "$(<go.mod)"

      - name: Test Backend Input Validation
        env:
          CONNECTION_STRING: ${{ secrets.POSTGRES_CONNECTION_STRING }}
          TOKEN_KEY: ${{ secrets.TOKEN_KEY }}
        run: |
          cd back_end
          go test -v .db/postgres/sqlc
